-- ============================================================
--  CEFISE ACADEMY — Banco de dados Supabase
--  Execute este SQL no painel do Supabase:
--  supabase.com → seu projeto → SQL Editor → New Query → Cole e execute
-- ============================================================

-- 1. TABELA DE PROFISSIONAIS
create table if not exists profissionais (
  id              bigint generated by default as identity primary key,
  user_id         uuid references auth.users(id) on delete cascade,
  nome            text not null,
  especialidade   text default 'Fisioterapeuta',
  crf             text,
  role            text default 'profissional', -- 'profissional' ou 'admin'
  created_at      timestamptz default now()
);

-- 2. TABELA DE PACIENTES
create table if not exists pacientes (
  id              bigint generated by default as identity primary key,
  nome            text not null,
  nasc            date,
  altura          numeric(4,2),
  peso            numeric(5,1),
  contato         text,
  profissional_id bigint references profissionais(id),
  created_at      timestamptz default now()
);

-- 3. TABELA DE AVALIAÇÕES
create table if not exists avaliacoes (
  id              bigint generated by default as identity primary key,
  paciente_id     bigint references pacientes(id) on delete cascade,
  profissional_id bigint references profissionais(id),
  data            date not null,
  tipo            text default 'avaliacao', -- 'avaliacao' ou 'reavaliacao'

  -- Anamnese
  cirurgia        text default 'nao',
  cirurgia_detalhe text,
  hdp             text default 'nao',
  hdp_detalhe     text,
  hda             text default 'nao',
  hda_detalhe     text,
  dor             text default 'nao',
  dor_detalhe     text,

  -- Testes especiais
  faber_d         text, faber_e text,
  fadir_d         text, fadir_e text,
  lasegue_d       text, lasegue_e text,
  slump_d         text, slump_e text,
  gonio_ri_d      numeric, gonio_ri_e numeric,
  gonio_re_d      numeric, gonio_re_e numeric,

  -- Força
  nordic          numeric,
  squat_d         numeric, squat_e numeric,
  bridge_d        numeric, bridge_e numeric,
  copenh_d        numeric, copenh_e numeric,
  core_d          numeric, core_e numeric,
  step_vd_d       numeric, step_vd_e numeric,
  step_qp_d       numeric, step_qp_e numeric,

  -- Estabilidade / Hop Tests
  sht_avg_d       numeric, sht_avg_e numeric,
  tht_avg_d       numeric, tht_avg_e numeric,
  cot_avg_d       numeric, cot_avg_e numeric,
  lunge_cm_d      numeric, lunge_cm_e numeric,
  lunge_ang_d     numeric, lunge_ang_e numeric,

  created_at      timestamptz default now()
);

-- ============================================================
--  SEGURANÇA — Row Level Security (RLS)
--  Cada profissional só vê seus próprios dados (recomendado)
--  OU todos podem ver tudo dentro da clínica (mais simples)
--  Aqui usamos a opção "todos da clínica veem tudo"
-- ============================================================

alter table profissionais  enable row level security;
alter table pacientes      enable row level security;
alter table avaliacoes     enable row level security;

-- Políticas: usuário autenticado pode ler/escrever tudo
create policy "auth users can read profissionais"
  on profissionais for select to authenticated using (true);

create policy "auth users can insert profissionais"
  on profissionais for insert to authenticated with check (true);

create policy "auth users can read pacientes"
  on pacientes for select to authenticated using (true);

create policy "auth users can insert pacientes"
  on pacientes for insert to authenticated with check (true);

create policy "auth users can update pacientes"
  on pacientes for update to authenticated using (true);

create policy "auth users can read avaliacoes"
  on avaliacoes for select to authenticated using (true);

create policy "auth users can insert avaliacoes"
  on avaliacoes for insert to authenticated with check (true);

-- ============================================================
--  PRIMEIRO USUÁRIO ADMINISTRADOR
--  Após criar sua conta no Supabase Auth, execute:
--
--  insert into profissionais (user_id, nome, especialidade, role)
--  values ('SEU_USER_ID_AQUI', 'Nome do Admin', 'Fisioterapeuta', 'admin');
--
--  Você encontra seu user_id em:
--  Supabase → Authentication → Users → copie o UUID do seu usuário
-- ============================================================
